apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: aspcoreweather 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: aspcoreweather 
    spec:
      containers:
        - name: aspcoreweather 
          image: pretiumwebapp.azurecr.io/aspcoreweather
          ports:
          - containerPort: 80